version: '3,8'
services:
  web:
    image: node:20
    container_name: web_dev
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    command: tail -f /dev/null
    ports:
      - "8080:8080"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSAWORD=root
      - MYSQL_DATABASE=webapp
      - MYSQL_USER=devuser
      - MYSQL_PASSAWORD=devpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSAWORD=root
    ports:
      - "8080"

  volumes:
  db_data

